zammad-nginx:
    environment:
        NGINX_SERVER_SCHEME: http
      VIRTUAL_HOST: ${VHOST:-servicedesk.alphaparking.de}
      LETSENCRYPT_HOST: ${LE_HOST:-support.domain.tld}
    <<: *zammad-service
    command: ["zammad-nginx"]
    expose:
      - "${NGINX_PORT:-7589}"
    ports:
      - "${NGINX_EXPOSE_PORT:-8080}:${NGINX_PORT:-8080}"
    depends_on:
      - zammad-railsserver
